name: Test

on: [push]

jobs:
  test-app:
    runs-on: ubuntu-latest
    container:
      # Make sure to grab the latest version of the Playwright image
      # https://playwright.dev/docs/docker#pull-the-image
      image: mcr.microsoft.com/playwright:v1.51.0-noble
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install dependencies
        run: yarn install

      - name: Run check
        run: |
          yarn turbo check --filter=@mealdrop/web

      - name: Run tests
        run: |
          yarn turbo test:ci --filter=@mealdrop/web
  test-ui:
    runs-on: ubuntu-latest
    container:
      # Make sure to grab the latest version of the Playwright image
      # https://playwright.dev/docs/docker#pull-the-image
      image: mcr.microsoft.com/playwright:v1.51.0-noble
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install dependencies
        run: yarn install

      - name: Run check
        run: |
          yarn turbo check --filter=@mealdrop/ui

      - name: Run tests
        run: |
          yarn turbo test:ci --filter=@mealdrop/ui
